version: '2'
services:
    memberadmin-app:
        image: memberadmin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://memberadmin-postgresql:5432/memberadmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=memberadmin-elasticsearch:9300
        ports:
            - 8080:8080
    memberadmin-postgresql:
        extends:
            file: postgresql.yml
            service: memberadmin-postgresql
    memberadmin-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: memberadmin-elasticsearch
